# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official

# Release signing configuration
SAFEKEYBOARD_UPLOAD_STORE_FILE=safekeyboard-release-key.keystore
SAFEKEYBOARD_UPLOAD_STORE_PASSWORD=safekeyboard2024
SAFEKEYBOARD_UPLOAD_KEY_ALIAS=safekeyboard-key-alias
SAFEKEYBOARD_UPLOAD_KEY_PASSWORD=safekeyboard2024
